### ISSUE TITLE
problem on make 

### ISSUE THREAD

**Issue by bv3un** [n7tae/mrefd#16]
sudo make
g++ -c -W -std=c++17 -MMD -c -DNO_DHT protocol.cpp -o protocol.o
protocol.cpp: In member function ‘void CProtocol::OnFirstPacketIn(std::unique_ptr<CPacket>&, const CIp&)’:
protocol.cpp:854:17: error: ‘class CReflector’ has no member named ‘PutDHTUsers’; did you mean ‘GetUsers’?
     g_Reflector.PutDHTUsers();
                 ^~~~~~~~~~~
Makefile:69: recipe for target 'protocol.o' failed
make: *** [protocol.o] Error 1

**Comment by n7tae** [comment]
Try a `make clean` and then a `make`.

**Comment by n7tae** [comment]
Sorry I didn't notice you were trying to build mrefd without DHT. This will be fixed in the next release cycle.
