### ISSUE TITLE
Failed to start mrefd

### ISSUE THREAD

**Issue by freelinknazionale** [n7tae/mrefd#19]
Hello,
I try to install mrefd but after run the instance appears this log:

apr 13 23:18:44 vm-test mrefd[11436]: Port=17000
apr 13 23:18:44 vm-test mrefd[11436]: MultiClient=false
apr 13 23:18:44 vm-test mrefd[11436]: Error starting reflector
apr 13 23:18:44 vm-test systemd[1]: mrefd.service: Main process exited, code=exited, status=1/FAILURE
apr 13 23:18:44 vm-test systemd[1]: mrefd.service: Failed with result 'exit-code'.
apr 13 23:18:44 vm-test systemd[1]: mrefd.service: Scheduled restart job, restart counter is at 5.
apr 13 23:18:44 vm-test systemd[1]: Stopped mrefd.
apr 13 23:18:44 vm-test systemd[1]: mrefd.service: Start request repeated too quickly.
apr 13 23:18:44 vm-test systemd[1]: mrefd.service: Failed with result 'exit-code'.
apr 13 23:18:44 vm-test systemd[1]: Failed to start mrefd.

the 3 config file are empty:

mrefd.blacklist  mrefd.interlink  mrefd.whitelist

file mrefd.mk is the following:

# mrefd compile-time configuration

# This is for the "install" target:
# If you don't like to use symbolic links for the mrefd.{cfg,blacklist,whitelist,interlink}
# files and you want to copy instead of link set this to "false".
USESYMLINK = false

# This is the folder where the executable file will be installed.
BINDIR = /usr/local/bin

# This is the folder where config files (or symbolic links) are located.
CFGDIR = /usr/local/etc

# For debugging support, set DEBUG to true.
DEBUG = false

# To disable DHT support, set DHT to false.
DHT = false

File mrefd.cfg is the following:

Callsign = M17-X15
Modules = BCX
IPv4BindAddr = 0.0.0.0
IPv6BindAddr = ::
Port = 17000
PidPath = /var/run/mrefd.pid
XmlPath = /var/log/mrefd.xml
WhitelistPath = /usr/local/etc/mrefd.whitelist
BlacklistPath = /usr/local/etc/mrefd.blacklist
InterlinkPath = /usr/local/etc/mrefd.interlink

Could you help me set up the software correctly? Thank you.

**Comment by n7tae** [comment]
Using your exact setup as described, I cannot reproduce the problem. Right before the "Error starting reflector" line should have been a report of how many lines were loaded from the mrefd.{whitelist,blacklist,interlink} files.

Do a `make clean` and set DEBUG to true in your mrefd.mk file. Then do a `make` and then a `make install`. After it fails, do a `gdb mrefd` in your build directory. After gdb comes up, do a `run /usr/local/etc/mrefd.cfg`. After mrefd crashes and you see the gdb prompt, do a `bt` and that will show you where mrefd is failing.

**Comment by freelinknazionale** [comment]
Executed make clean and changed DEBUG in true, and then make and make install.
Now running!

root@vm-test:~/mrefd# sudo journalctl -u mrefd -f
-- Journal begins at Thu 2023-04-13 22:35:26 CEST. --
apr 14 16:07:06 vm-test mrefd[1654]: BlacklistPath='/usr/local/etc/mrefd.blacklist'
apr 14 16:07:06 vm-test mrefd[1654]: InterlinkPath='/usr/local/etc/mrefd.interlink'
apr 14 16:07:06 vm-test mrefd[1654]: Port=17000
apr 14 16:07:06 vm-test mrefd[1654]: MultiClient=false
apr 14 16:07:06 vm-test mrefd[1654]: Gatekeeper loaded 0 lines from /usr/local/etc/mrefd.whitelist
apr 14 16:07:06 vm-test mrefd[1654]: Gatekeeper loaded 0 lines from /usr/local/etc/mrefd.blacklist
apr 14 16:07:06 vm-test mrefd[1654]: Gatekeeper loaded 0 lines from /usr/local/etc/mrefd.interlink
apr 14 16:07:06 vm-test mrefd[1654]: Listening on 0.0.0.0:17000
apr 14 16:07:06 vm-test mrefd[1654]: Listening on [::]:17000
apr 14 16:07:06 vm-test mrefd[1654]: Reflector M17-X15 started and listening

**Comment by freelinknazionale** [comment]
![M17-DashBoard](https://user-images.githubusercontent.com/81030411/232069487-0d792d44-1204-451f-848b-a61e33825357.PNG)

dashboard also seems to work

![M17-DashBoard1](https://user-images.githubusercontent.com/81030411/232069707-9fae8382-c6f5-473b-bcb7-83b76f7714e3.PNG)

now can you help me connect an ESP32 client? I have already installed ESP32IGate firmware V0.9 ESP32DR MODEL: Simple

What configurations do I have to make on the server? What configurations do I have to make on the client?

**Comment by n7tae** [comment]
Sorry, I don't know anything about the ESP32.
