### ISSUE TITLE
Versioning for packaging mrefd

### ISSUE THREAD

**Issue by marcoSchr** [n7tae/mrefd#20]
I want to package mrefd. For this I will need to know which version mrefd is and which commit corresponds to this version.
I see the version is in `version.cpp`.

You have had tags for versions before. It would be helpful to have tags for versions again.

At the moment I use commit e579746edbcfce78df7ef6b212066b954fb3f0ff as version 0.11.3. Would this be correct?

**Comment by n7tae** [comment]
Tag added to your identified commit. Please note that the latest "released" version of mrefd will always be in `master` and this can be several commits beyond a tag. This is because I will only bump the version if a commit fixes a bug or there is a change in capability.

**Comment by marcoSchr** [comment]
Thank you for creating the tag.

When packaging an application, there should only ever be 1 commit for one version.
This would be the commit you tag.

For me to package mrefd it would be enough, if you create a tag, whenever there is a new version.
