### ISSUE TITLE
make issues

### ISSUE THREAD

**Issue by DumbTermin0ls** [n7tae/mrefd#21]
Hi, facing issue below, tried 3 distros (Deb10 / Ubuntu Desktop 20.04 and Ubuntu Server 20.04) all report the same issue

shehzad@m17:~/opendht/build$ make
Scanning dependencies of target opendht
[  2%] Building CXX object CMakeFiles/opendht.dir/src/base64.cpp.o
[  5%] Building CXX object CMakeFiles/opendht.dir/src/utils.cpp.o
[  8%] Building CXX object CMakeFiles/opendht.dir/src/crypto.cpp.o
In file included from /home/shehzad/opendht/include/opendht/crypto.h:22,
                 from /home/shehzad/opendht/src/crypto.cpp:20:
/home/shehzad/opendht/include/opendht/infohash.h: In member function ‘constexpr auto fmt::v6::formatter<dht::Hash<N> >::format(const dht::Hash<N>&, fmt::v6::format_context&) const’:
/home/shehzad/opendht/include/opendht/infohash.h:402:36: error: ‘format’ is not a member of ‘fmt::v6::formatter<fmt::v6::basic_string_view<char> >’
  402 |     return formatter<string_view>::format(c.to_view(), ctx);
      |                                    ^~~~~~
/home/shehzad/opendht/src/crypto.cpp: In function ‘dht::Blob dht::crypto::aesEncrypt(const uint8_t*, size_t, const Blob&)’:
/home/shehzad/opendht/src/crypto.cpp:99:49: warning: ‘void nettle_gcm_aes_set_key(gcm_aes_ctx*, size_t, const uint8_t*)’ is deprecated [-Wdeprecated-declarations]
   99 |     gcm_aes_set_key(&aes, key.size(), key.data());
      |                                                 ^
In file included from /home/shehzad/opendht/src/crypto.cpp:27:
/usr/include/nettle/gcm.h:268:1: note: declared here
  268 | gcm_aes_set_key(struct gcm_aes_ctx *ctx,
      | ^~~~~~~~~~~~~~~
/home/shehzad/opendht/src/crypto.cpp:99:49: warning: ‘void nettle_gcm_aes_set_key(gcm_aes_ctx*, size_t, const uint8_t*)’ is deprecated [-Wdeprecated-declarations]
   99 |     gcm_aes_set_key(&aes, key.size(), key.data());
      |                                                 ^
In file included from /home/shehzad/opendht/src/crypto.cpp:27:
/usr/include/nettle/gcm.h:268:1: note: declared here
  268 | gcm_aes_set_key(struct gcm_aes_ctx *ctx,
      | ^~~~~~~~~~~~~~~
/home/shehzad/opendht/src/crypto.cpp:100:49: warning: ‘void nettle_gcm_aes_set_iv(gcm_aes_ctx*, size_t, const uint8_t*)’ is deprecated [-Wdeprecated-declarations]
  100 |     gcm_aes_set_iv(&aes, GCM_IV_SIZE, ret.data());
      |                                                 ^
In file included from /home/shehzad/opendht/src/crypto.cpp:27:
/usr/include/nettle/gcm.h:272:1: note: declared here
  272 | gcm_aes_set_iv(struct gcm_aes_ctx *ctx,
      | ^~~~~~~~~~~~~~
/home/shehzad/opendht/src/crypto.cpp:100:49: warning: ‘void nettle_gcm_aes_set_iv(gcm_aes_ctx*, size_t, const uint8_t*)’ is deprecated [-Wdeprecated-declarations]
  100 |     gcm_aes_set_iv(&aes, GCM_IV_SIZE, ret.data());
      |                                                 ^
In file included from /home/shehzad/opendht/src/crypto.cpp:27:
/usr/include/nettle/gcm.h:272:1: note: declared here
  272 | gcm_aes_set_iv(struct gcm_aes_ctx *ctx,
      | ^~~~~~~~~~~~~~
/home/shehzad/opendht/src/crypto.cpp:101:70: warning: ‘void nettle_gcm_aes_encrypt(gcm_aes_ctx*, size_t, uint8_t*, const uint8_t*)’ is deprecated [-Wdeprecated-declarations]
  101 |     gcm_aes_encrypt(&aes, data_length, ret.data() + GCM_IV_SIZE, data);
      |                                                                      ^
In file included from /home/shehzad/opendht/src/crypto.cpp:27:
/usr/include/nettle/gcm.h:280:1: note: declared here
  280 | gcm_aes_encrypt(struct gcm_aes_ctx *ctx,
      | ^~~~~~~~~~~~~~~
/home/shehzad/opendht/src/crypto.cpp:101:70: warning: ‘void nettle_gcm_aes_encrypt(gcm_aes_ctx*, size_t, uint8_t*, const uint8_t*)’ is deprecated [-Wdeprecated-declarations]
  101 |     gcm_aes_encrypt(&aes, data_length, ret.data() + GCM_IV_SIZE, data);
      |                                                                      ^
In file included from /home/shehzad/opendht/src/crypto.cpp:27:
/usr/include/nettle/gcm.h:280:1: note: declared here
  280 | gcm_aes_encrypt(struct gcm_aes_ctx *ctx,
      | ^~~~~~~~~~~~~~~
/home/shehzad/opendht/src/crypto.cpp:102:81: warning: ‘void nettle_gcm_aes_digest(gcm_aes_ctx*, size_t, uint8_t*)’ is deprecated [-Wdeprecated-declarations]
  102 |     gcm_aes_digest(&aes, GCM_DIGEST_SIZE, ret.data() + GCM_IV_SIZE + data_length);
      |                                                                                 ^
In file included from /home/shehzad/opendht/src/crypto.cpp:27:
/usr/include/nettle/gcm.h:290:1: note: declared here
  290 | gcm_aes_digest(struct gcm_aes_ctx *ctx, size_t length, uint8_t *digest)
      | ^~~~~~~~~~~~~~
/home/shehzad/opendht/src/crypto.cpp:102:81: warning: ‘void nettle_gcm_aes_digest(gcm_aes_ctx*, size_t, uint8_t*)’ is deprecated [-Wdeprecated-declarations]
  102 |     gcm_aes_digest(&aes, GCM_DIGEST_SIZE, ret.data() + GCM_IV_SIZE + data_length);
      |                                                                                 ^
In file included from /home/shehzad/opendht/src/crypto.cpp:27:
/usr/include/nettle/gcm.h:290:1: note: declared here
  290 | gcm_aes_digest(struct gcm_aes_ctx *ctx, size_t length, uint8_t *digest)
      | ^~~~~~~~~~~~~~
/home/shehzad/opendht/src/crypto.cpp: In function ‘dht::Blob dht::crypto::aesDecrypt(const uint8_t*, size_t, const Blob&)’:
/home/shehzad/opendht/src/crypto.cpp:126:49: warning: ‘void nettle_gcm_aes_set_key(gcm_aes_ctx*, size_t, const uint8_t*)’ is deprecated [-Wdeprecated-declarations]
  126 |     gcm_aes_set_key(&aes, key.size(), key.data());
      |                                                 ^
In file included from /home/shehzad/opendht/src/crypto.cpp:27:
/usr/include/nettle/gcm.h:268:1: note: declared here
  268 | gcm_aes_set_key(struct gcm_aes_ctx *ctx,
      | ^~~~~~~~~~~~~~~
/home/shehzad/opendht/src/crypto.cpp:126:49: warning: ‘void nettle_gcm_aes_set_key(gcm_aes_ctx*, size_t, const uint8_t*)’ is deprecated [-Wdeprecated-declarations]
  126 |     gcm_aes_set_key(&aes, key.size(), key.data());
      |                                                 ^
In file included from /home/shehzad/opendht/src/crypto.cpp:27:
/usr/include/nettle/gcm.h:268:1: note: declared here
  268 | gcm_aes_set_key(struct gcm_aes_ctx *ctx,
      | ^~~~~~~~~~~~~~~
/home/shehzad/opendht/src/crypto.cpp:127:43: warning: ‘void nettle_gcm_aes_set_iv(gcm_aes_ctx*, size_t, const uint8_t*)’ is deprecated [-Wdeprecated-declarations]
  127 |     gcm_aes_set_iv(&aes, GCM_IV_SIZE, data);
      |                                           ^
In file included from /home/shehzad/opendht/src/crypto.cpp:27:
/usr/include/nettle/gcm.h:272:1: note: declared here
  272 | gcm_aes_set_iv(struct gcm_aes_ctx *ctx,
      | ^~~~~~~~~~~~~~
/home/shehzad/opendht/src/crypto.cpp:127:43: warning: ‘void nettle_gcm_aes_set_iv(gcm_aes_ctx*, size_t, const uint8_t*)’ is deprecated [-Wdeprecated-declarations]
  127 |     gcm_aes_set_iv(&aes, GCM_IV_SIZE, data);
      |                                           ^
In file included from /home/shehzad/opendht/src/crypto.cpp:27:
/usr/include/nettle/gcm.h:272:1: note: declared here
  272 | gcm_aes_set_iv(struct gcm_aes_ctx *ctx,
      | ^~~~~~~~~~~~~~
/home/shehzad/opendht/src/crypto.cpp:131:66: warning: ‘void nettle_gcm_aes_decrypt(gcm_aes_ctx*, size_t, uint8_t*, const uint8_t*)’ is deprecated [-Wdeprecated-declarations]
  131 |     gcm_aes_decrypt(&aes, data_sz, ret.data(), data + GCM_IV_SIZE);
      |                                                                  ^
In file included from /home/shehzad/opendht/src/crypto.cpp:27:
/usr/include/nettle/gcm.h:285:1: note: declared here
  285 | gcm_aes_decrypt(struct gcm_aes_ctx *ctx,
      | ^~~~~~~~~~~~~~~
/home/shehzad/opendht/src/crypto.cpp:131:66: warning: ‘void nettle_gcm_aes_decrypt(gcm_aes_ctx*, size_t, uint8_t*, const uint8_t*)’ is deprecated [-Wdeprecated-declarations]
  131 |     gcm_aes_decrypt(&aes, data_sz, ret.data(), data + GCM_IV_SIZE);
      |                                                                  ^
In file included from /home/shehzad/opendht/src/crypto.cpp:27:
/usr/include/nettle/gcm.h:285:1: note: declared here
  285 | gcm_aes_decrypt(struct gcm_aes_ctx *ctx,
      | ^~~~~~~~~~~~~~~
/home/shehzad/opendht/src/crypto.cpp:132:56: warning: ‘void nettle_gcm_aes_digest(gcm_aes_ctx*, size_t, uint8_t*)’ is deprecated [-Wdeprecated-declarations]
  132 |     gcm_aes_digest(&aes, GCM_DIGEST_SIZE, digest.data());
      |                                                        ^
In file included from /home/shehzad/opendht/src/crypto.cpp:27:
/usr/include/nettle/gcm.h:290:1: note: declared here
  290 | gcm_aes_digest(struct gcm_aes_ctx *ctx, size_t length, uint8_t *digest)
      | ^~~~~~~~~~~~~~
/home/shehzad/opendht/src/crypto.cpp:132:56: warning: ‘void nettle_gcm_aes_digest(gcm_aes_ctx*, size_t, uint8_t*)’ is deprecated [-Wdeprecated-declarations]
  132 |     gcm_aes_digest(&aes, GCM_DIGEST_SIZE, digest.data());
      |                                                        ^
In file included from /home/shehzad/opendht/src/crypto.cpp:27:
/usr/include/nettle/gcm.h:290:1: note: declared here
  290 | gcm_aes_digest(struct gcm_aes_ctx *ctx, size_t length, uint8_t *digest)
      | ^~~~~~~~~~~~~~
/home/shehzad/opendht/src/crypto.cpp:139:55: warning: ‘void nettle_gcm_aes_set_key(gcm_aes_ctx*, size_t, const uint8_t*)’ is deprecated [-Wdeprecated-declarations]
  139 |         gcm_aes_set_key(&aes_d, key.size(), key.data());
      |                                                       ^
In file included from /home/shehzad/opendht/src/crypto.cpp:27:
/usr/include/nettle/gcm.h:268:1: note: declared here
  268 | gcm_aes_set_key(struct gcm_aes_ctx *ctx,
      | ^~~~~~~~~~~~~~~
/home/shehzad/opendht/src/crypto.cpp:139:55: warning: ‘void nettle_gcm_aes_set_key(gcm_aes_ctx*, size_t, const uint8_t*)’ is deprecated [-Wdeprecated-declarations]
  139 |         gcm_aes_set_key(&aes_d, key.size(), key.data());
      |                                                       ^
In file included from /home/shehzad/opendht/src/crypto.cpp:27:
/usr/include/nettle/gcm.h:268:1: note: declared here
  268 | gcm_aes_set_key(struct gcm_aes_ctx *ctx,
      | ^~~~~~~~~~~~~~~
/home/shehzad/opendht/src/crypto.cpp:140:49: warning: ‘void nettle_gcm_aes_set_iv(gcm_aes_ctx*, size_t, const uint8_t*)’ is deprecated [-Wdeprecated-declarations]
  140 |         gcm_aes_set_iv(&aes_d, GCM_IV_SIZE, data);
      |                                                 ^
In file included from /home/shehzad/opendht/src/crypto.cpp:27:
/usr/include/nettle/gcm.h:272:1: note: declared here
  272 | gcm_aes_set_iv(struct gcm_aes_ctx *ctx,
      | ^~~~~~~~~~~~~~
/home/shehzad/opendht/src/crypto.cpp:140:49: warning: ‘void nettle_gcm_aes_set_iv(gcm_aes_ctx*, size_t, const uint8_t*)’ is deprecated [-Wdeprecated-declarations]
  140 |         gcm_aes_set_iv(&aes_d, GCM_IV_SIZE, data);
      |                                                 ^
In file included from /home/shehzad/opendht/src/crypto.cpp:27:
/usr/include/nettle/gcm.h:272:1: note: declared here
  272 | gcm_aes_set_iv(struct gcm_aes_ctx *ctx,
      | ^~~~~~~~~~~~~~
/home/shehzad/opendht/src/crypto.cpp:141:54: warning: ‘void nettle_gcm_aes_update(gcm_aes_ctx*, size_t, const uint8_t*)’ is deprecated [-Wdeprecated-declarations]
  141 |         gcm_aes_update(&aes_d, ret.size(), ret.data());
      |                                                      ^
In file included from /home/shehzad/opendht/src/crypto.cpp:27:
/usr/include/nettle/gcm.h:276:1: note: declared here
  276 | gcm_aes_update(struct gcm_aes_ctx *ctx,
      | ^~~~~~~~~~~~~~
/home/shehzad/opendht/src/crypto.cpp:141:54: warning: ‘void nettle_gcm_aes_update(gcm_aes_ctx*, size_t, const uint8_t*)’ is deprecated [-Wdeprecated-declarations]
  141 |         gcm_aes_update(&aes_d, ret.size(), ret.data());
      |                                                      ^
In file included from /home/shehzad/opendht/src/crypto.cpp:27:
/usr/include/nettle/gcm.h:276:1: note: declared here
  276 | gcm_aes_update(struct gcm_aes_ctx *ctx,
      | ^~~~~~~~~~~~~~
/home/shehzad/opendht/src/crypto.cpp:142:71: warning: ‘void nettle_gcm_aes_encrypt(gcm_aes_ctx*, size_t, uint8_t*, const uint8_t*)’ is deprecated [-Wdeprecated-declarations]
  142 |         gcm_aes_encrypt(&aes_d, ret.size(), ret_tmp.data(), ret.data());
      |                                                                       ^
In file included from /home/shehzad/opendht/src/crypto.cpp:27:
/usr/include/nettle/gcm.h:280:1: note: declared here
  280 | gcm_aes_encrypt(struct gcm_aes_ctx *ctx,
      | ^~~~~~~~~~~~~~~
/home/shehzad/opendht/src/crypto.cpp:142:71: warning: ‘void nettle_gcm_aes_encrypt(gcm_aes_ctx*, size_t, uint8_t*, const uint8_t*)’ is deprecated [-Wdeprecated-declarations]
  142 |         gcm_aes_encrypt(&aes_d, ret.size(), ret_tmp.data(), ret.data());
      |                                                                       ^
In file included from /home/shehzad/opendht/src/crypto.cpp:27:
/usr/include/nettle/gcm.h:280:1: note: declared here
  280 | gcm_aes_encrypt(struct gcm_aes_ctx *ctx,
      | ^~~~~~~~~~~~~~~
/home/shehzad/opendht/src/crypto.cpp:143:62: warning: ‘void nettle_gcm_aes_digest(gcm_aes_ctx*, size_t, uint8_t*)’ is deprecated [-Wdeprecated-declarations]
  143 |         gcm_aes_digest(&aes_d, GCM_DIGEST_SIZE, digest.data());
      |                                                              ^
In file included from /home/shehzad/opendht/src/crypto.cpp:27:
/usr/include/nettle/gcm.h:290:1: note: declared here
  290 | gcm_aes_digest(struct gcm_aes_ctx *ctx, size_t length, uint8_t *digest)
      | ^~~~~~~~~~~~~~
/home/shehzad/opendht/src/crypto.cpp:143:62: warning: ‘void nettle_gcm_aes_digest(gcm_aes_ctx*, size_t, uint8_t*)’ is deprecated [-Wdeprecated-declarations]
  143 |         gcm_aes_digest(&aes_d, GCM_DIGEST_SIZE, digest.data());
      |                                                              ^
In file included from /home/shehzad/opendht/src/crypto.cpp:27:
/usr/include/nettle/gcm.h:290:1: note: declared here
  290 | gcm_aes_digest(struct gcm_aes_ctx *ctx, size_t length, uint8_t *digest)
      | ^~~~~~~~~~~~~~
make[2]: *** [CMakeFiles/opendht.dir/build.make:89: CMakeFiles/opendht.dir/src/crypto.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:315: CMakeFiles/opendht.dir/all] Error 2
make: *** [Makefile:141: all] Error 2
shehzad@m17:~/opendht/build$

**Comment by n7tae** [comment]
Wow, not sure why the strike-thru font is showing up in your issue report, but anyway...

This is not a problem with _mrefd_. I suspect you're trying to build the latest version of OpenDHT in an older OS. The OpenDHT developers tend to use the latest OSes as they added features and fixes. There are probably a couple of different ways you can solve this:

1. Try a later OS. For example, Ubuntu 22.04 will build the latest version of OpenDHT just fine.
2. Try an earlier version of OpenDHT. Currently OpenDHT is at V#3.0.0. I don't know how far back you need to go, 2.6.*, or 2.5.* or maybe 2.4.*.

Because this is not a problem with _mrefd_ but rather OpenDHT, I'm going to close this issue.

**Comment by bi7jta** [comment]
The same problem when make "https://github.com/savoirfairelinux/opendht.git".
 
lsb_release -a
No LSB modules are available.
Distributor ID: Debian
Description:    Debian GNU/Linux 11 (bullseye)
Release:        11
Codename:       bullseye


```
make
Scanning dependencies of target opendht
[  2%] Building CXX object CMakeFiles/opendht.dir/src/base64.cpp.o
[  5%] Building CXX object CMakeFiles/opendht.dir/src/utils.cpp.o
[  8%] Building CXX object CMakeFiles/opendht.dir/src/crypto.cpp.o
In file included from /root/M17Relfector/opendht/include/opendht/crypto.h:22,
                 from /root/M17Relfector/opendht/src/crypto.cpp:20:
/root/M17Relfector/opendht/include/opendht/infohash.h: In member function ‘constexpr auto fmt::v7::formatter<dht::Hash<N> >::format(const dht::Hash<N>&, fmt::v7::format_context&) const’:
/root/M17Relfector/opendht/include/opendht/infohash.h:402:36: error: ‘format’ is not a member of ‘fmt::v7::formatter<fmt::v7::basic_string_view<char> >’
  402 |     return formatter<string_view>::format(c.to_view(), ctx);
      |                                    ^~~~~~
/root/M17Relfector/opendht/src/crypto.cpp: In function ‘dht::Blob dht::crypto::aesEncrypt(const uint8_t*, size_t, const Blob&)’:
/root/M17Relfector/opendht/src/crypto.cpp:97:49: warning: ‘void nettle_gcm_aes_set_key(gcm_aes_ctx*, size_t, const uint8_t*)’ is deprecated [-Wdeprecated-declarations]
   97 |     gcm_aes_set_key(&aes, key.size(), key.data());
      |                                                 ^
In file included from /root/M17Relfector/opendht/src/crypto.cpp:27:
/usr/include/nettle/gcm.h:268:1: note: declared here
  268 | gcm_aes_set_key(struct gcm_aes_ctx *ctx,
      | ^~~~~~~~~~~~~~~
/root/M17Relfector/opendht/src/crypto.cpp:98:49: warning: ‘void nettle_gcm_aes_set_iv(gcm_aes_ctx*, size_t, const uint8_t*)’ is deprecated [-Wdeprecated-declarations]
   98 |     gcm_aes_set_iv(&aes, GCM_IV_SIZE, ret.data());
      |                                                 ^
In file included from /root/M17Relfector/opendht/src/crypto.cpp:27:
/usr/include/nettle/gcm.h:272:1: note: declared here
  272 | gcm_aes_set_iv(struct gcm_aes_ctx *ctx,
      | ^~~~~~~~~~~~~~
/root/M17Relfector/opendht/src/crypto.cpp:99:70: warning: ‘void nettle_gcm_aes_encrypt(gcm_aes_ctx*, size_t, uint8_t*, const uint8_t*)’ is deprecated [-Wdeprecated-declarations]
   99 |     gcm_aes_encrypt(&aes, data_length, ret.data() + GCM_IV_SIZE, data);
      |                                                                      ^
In file included from /root/M17Relfector/opendht/src/crypto.cpp:27:
/usr/include/nettle/gcm.h:280:1: note: declared here
  280 | gcm_aes_encrypt(struct gcm_aes_ctx *ctx,
      | ^~~~~~~~~~~~~~~
/root/M17Relfector/opendht/src/crypto.cpp:100:81: warning: ‘void nettle_gcm_aes_digest(gcm_aes_ctx*, size_t, uint8_t*)’ is deprecated [-Wdeprecated-declarations]
  100 |     gcm_aes_digest(&aes, GCM_DIGEST_SIZE, ret.data() + GCM_IV_SIZE + data_length);
      |                                                                                 ^
In file included from /root/M17Relfector/opendht/src/crypto.cpp:27:
/usr/include/nettle/gcm.h:290:1: note: declared here
  290 | gcm_aes_digest(struct gcm_aes_ctx *ctx, size_t length, uint8_t *digest)
      | ^~~~~~~~~~~~~~
/root/M17Relfector/opendht/src/crypto.cpp: In function ‘dht::Blob dht::crypto::aesDecrypt(const uint8_t*, size_t, const Blob&)’:
/root/M17Relfector/opendht/src/crypto.cpp:122:49: warning: ‘void nettle_gcm_aes_set_key(gcm_aes_ctx*, size_t, const uint8_t*)’ is deprecated [-Wdeprecated-declarations]
  122 |     gcm_aes_set_key(&aes, key.size(), key.data());
      |                                                 ^
In file included from /root/M17Relfector/opendht/src/crypto.cpp:27:
/usr/include/nettle/gcm.h:268:1: note: declared here
  268 | gcm_aes_set_key(struct gcm_aes_ctx *ctx,
      | ^~~~~~~~~~~~~~~
/root/M17Relfector/opendht/src/crypto.cpp:123:43: warning: ‘void nettle_gcm_aes_set_iv(gcm_aes_ctx*, size_t, const uint8_t*)’ is deprecated [-Wdeprecated-declarations]
  123 |     gcm_aes_set_iv(&aes, GCM_IV_SIZE, data);
      |                                           ^
In file included from /root/M17Relfector/opendht/src/crypto.cpp:27:
/usr/include/nettle/gcm.h:272:1: note: declared here
  272 | gcm_aes_set_iv(struct gcm_aes_ctx *ctx,
      | ^~~~~~~~~~~~~~
/root/M17Relfector/opendht/src/crypto.cpp:127:66: warning: ‘void nettle_gcm_aes_decrypt(gcm_aes_ctx*, size_t, uint8_t*, const uint8_t*)’ is deprecated [-Wdeprecated-declarations]
  127 |     gcm_aes_decrypt(&aes, data_sz, ret.data(), data + GCM_IV_SIZE);
      |                                                                  ^
In file included from /root/M17Relfector/opendht/src/crypto.cpp:27:
/usr/include/nettle/gcm.h:285:1: note: declared here
  285 | gcm_aes_decrypt(struct gcm_aes_ctx *ctx,
      | ^~~~~~~~~~~~~~~
/root/M17Relfector/opendht/src/crypto.cpp:128:56: warning: ‘void nettle_gcm_aes_digest(gcm_aes_ctx*, size_t, uint8_t*)’ is deprecated [-Wdeprecated-declarations]
  128 |     gcm_aes_digest(&aes, GCM_DIGEST_SIZE, digest.data());
      |                                                        ^
In file included from /root/M17Relfector/opendht/src/crypto.cpp:27:
/usr/include/nettle/gcm.h:290:1: note: declared here
  290 | gcm_aes_digest(struct gcm_aes_ctx *ctx, size_t length, uint8_t *digest)
      | ^~~~~~~~~~~~~~
make[2]: *** [CMakeFiles/opendht.dir/build.make:108: CMakeFiles/opendht.dir/src/crypto.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:334: CMakeFiles/opendht.dir/all] Error 2
make: *** [Makefile:160: all] Error 2


```

**Comment by n7tae** [comment]
This looks like your missing some required dependencies, specifically libfmt-dev. 

`sudo apt install libncurses5-dev libreadline-dev nettle-dev libgnutls28-dev libargon2-0-dev libmsgpack-dev  libssl-dev libfmt-dev libjsoncpp-dev libhttp-parser-dev libasio-dev cmake pkg-config libcppunit-dev`

Also, building this in /root is probably not the best idea. Besides, you don't need root privileges to do `make`.
