### ISSUE TITLE
Multiple connections from same IP

### ISSUE THREAD

**Issue by nostar** [n7tae/mrefd#6]
What do you think about allowing connections from the same IP and even *gasp* callsign?  The reasons are piling up for me to want to  be able to connect to the same reflector more than once.  The obvious is to  be able to back monitor, but other reason include the ability to connect to 2 different modules on the same reflector at the same time.  I have the M172DMR/DMR2M17 utils working well now, and have 2 modules of my reflector connected to 2 different multimode reflector neworks in my area.  I would like myself and others to be able to connect to both of them with separate clients (someday hotspots) for example.  Your thoughts?

**Comment by n7tae** [comment]
You can have clients with the same callsign. The IP restriction is in there mostly because of the ubiquity of hot-spots. It's too easy for someone to lock up the reflector with two, cross-talking hot-spots linked to the same module.

**Comment by n7tae** [comment]
There is a new branch, "issue#6" that will allow clients with the same IP **as long as they are using different ports**. This means that every client should be connecting with ephemeral ports, i.e., it should be written into the M17 spec.

It is statistically possible that a second client might be refused if it happened to choose an ephemeral port that the first client is already using. In that case, just start up the second client again.

If M17-aware hot-spots become as popular as MMDVM hot-spot, we'll probably have to revisit this.

Let me know if this new branch meets your needs.

**Comment by nostar** [comment]
Excellent.  Initial testing shows that it works correctly unless there is a connection from a client with the same IP *and* same callsign as another.  One time only that client was unable to send or receive, other times it seems like all clients stopped receiving and sending after that connection.

**Comment by n7tae** [comment]
Yikes! I'm having a little trouble parsing the last sentence. If two clients using the same IP and callsign are linked it locks up the reflector?

**Comment by nostar** [comment]
No it never locks up the reflector, it just stopped the other clients connected via the same IP from receiving or transmitting...  Or so I thought.  I have tried to reproduce that behavior many times now, and I can not, so I think I may have imagined it.  As it stand right now, if a second connection happens from same IP *and* same callsign, just that second connection with same callsign connects fine, appears to be working but just doesn't TX or RX anything.

**Comment by n7tae** [comment]
Good info. I pushed up a change to the CClient == operator. Try it again.

**Comment by nostar** [comment]
Yes, this works correctly now, thanks!

**Comment by nostar** [comment]
And now for the $2 question.  Would you be interested in running this version on M17-USA?

**Comment by n7tae** [comment]
The issue#6 branch adds a new option to ./rconfig. Sysops can opt-in this support if they want it. The default is that support is off.

M17-USA is currently running with this option.

**Comment by nostar** [comment]
Great!
