### ISSUE TITLE
Out of Memory Error in Chrome

### ISSUE THREAD

**Issue by jrwoodman** [n7tae/mrefd#9]
When monitoring mrefd via the web interface, within a few hours Chrome will complain of being out of memory and will not auto-reload the page. A refresh fixes the problem but perhaps the cause should be investigated?

Thanks and 73,
Russ - K5TUX

**Comment by n7tae** [comment]
Thanks Russ. The mrefd dashboard is actually in a different repo, https://github.com/M17-project/ref-dash. You should open your issue there.
